### ISSUE TITLE
essentialmode?

### ISSUE THREAD

**Issue by DJShocker** [LambentLight/Metadata#12]
Is there a way you can add support for essentialmode? Besides, their setup with ESX is just insane. I've never been more confused in my entire life.

**Comment by justalemon** [comment]
I have moved this issue from the main repo to the one that contains the list of resources that can be installed.

**Comment by justalemon** [comment]
So, there are a lot of reasons why is not possible to install essentialmode and esx:

* The modes are terribly designed that you need to install it and launch it in a specific way
* To just install the base of esx, you need like 10 resources for just one gamemode (instead of one resource containing everything)
* Even if we install everything, the user still needs to do a lot of changes to make it work

**Comment by justalemon** [comment]
I have managed to add every single ES and ESX official script into the Beta installer:

![image](https://user-images.githubusercontent.com/11861253/70938818-baea0880-2025-11ea-8fcc-50d642d4bba8.png)

Because the new instal system is not yet available, I'm not going to close this issue yet.

**Comment by justalemon** [comment]
Use LambentLight 2.0 or higher to access the new installer format and install ES/ESX.
